### ISSUE TITLE
CDN hosting

### ISSUE THREAD

**Issue by djave-co** [andybrewer/mvp#24]
It would be great if this was part of a CDN like https://cdnjs.com. I think this then makes it available to online apps like CodePen that use their API.

They have a page in their docs about how to add a library here:
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md

I'd be happy to take a look if its anything you need help with.

**Comment by andybrewer** [comment]
Thanks @djave-co! It would be awesome to include it there. Is that something you'd be interested in doing or do you need anything on my end?

**Comment by v4dkou** [comment]
CodePen can load any external URL, so a link to the CSS on github.io already does the job
https://codepen.io/vadkou/pen/YzyNrZX

I can imagine that using github.io as a CDN might not suit you. 
Probably because you want to use specific versions of the CSS as a dependency, so your MVP doesn't change mid-development.

NPM solves dependency versioning (and is arguably a better fit for developers who use packaging tools like Webpack or Parcel).
If you publish the library to NPM, it will also be available in the https://unpkg.com/ CDN
https://blog.codepen.io/2017/08/11/using-resources-npm-codepen/

Two birds, one stone :)

Even if somebody needs cdnjs.com specifically, I would advise publishing to NPM first.
https://github.com/andybrewer/mvp/issues/30

**Comment by andybrewer** [comment]
Thanks @djave-co and @v4dkou, it's now listed as an NPM package here:
NPM: https://www.npmjs.com/package/mvp.css
Unpkg: https://unpkg.com/mvp.css
