### ISSUE TITLE
Cisco Umbrella Blocking Page

### ISSUE THREAD

**Issue by hasokeric** [andybrewer/mvp#6]
![image](https://user-images.githubusercontent.com/403818/77542533-b337cc80-6e7c-11ea-95d8-fd7c3f84f1ae.png)

**Comment by philp** [comment]
Nope. Something nasty happened in network routing, or maybe IP packets being considered as spoofed because of routing via a misconfigured VPN. Because an OpenDNS check shows up zero tagged submissions for the domain:

https://community.opendns.com/domaintagging/search/?q=andybrewer.github.io

Also suspicious that the check diagnostics show the trailing slash as an encoded `%2F`. If you tried to route to that URL, it would always fail.

**Comment by andybrewer** [comment]
This is a GitHub project page with static HTML/CSS, so I'm not sure why it would be triggering any security threats. I'll go ahead and close since this seems like an isolated incident.
