### ISSUE TITLE
Headings & Forms don't create a newline after them

### ISSUE THREAD

**Issue by michealp-coder** [andybrewer/mvp#63]
It appears that only h1 headings create a newline after them. `H2`-`H6` & `FORM` don't create newlines after their block.

Here is an example code

https://codepen.io/michealp/pen/dyvNNzb

Notice how "The all-in-one" isn't on a newline from the h1 of "Todo Platform..."

Or how the `FORM` is being smashed with he `P` content.

Or notice how the `h2` of "An h2 headlines goes here on the page." doesn't create a newline and instead the link is on the same line.

**Comment by michealp-coder** [comment]
Here's a screenshot showing how the `H2-H6` (or `form`) is colliding with the `p` content.

<img width="1127" alt="Screen Shot 2021-05-20 at 10 12 00 AM" src="https://user-images.githubusercontent.com/84467623/119014298-73278900-b95d-11eb-90b1-1e8e00f22185.png">

**Comment by andybrewer** [comment]
Correct. `<section>` tags are flex boxes. If you change it to an `<article>` tag, I think it'll line break appropriately for you, but it'll be left-aligned. This is by design, so developers have a flexbox and non-flexbox option without having to create custom CSS.

To get centered text with line breaks, you have a few options:
1. Use a `<header>` tag inside of a `<section>` tag
2. Use an `<article>` tag or a `<div>` tag and then create custom CSS to center certain content
3. Use a `<section>` tag and apply custom CSS to certain elements to make them full-width

**Comment by michealp-coder** [comment]
Hi @andybrewer 

So I went down the path of Option #1 and adding a `header` tag inside of a `section` now made anything inside the `header` have line breaks.

The trouble is that any other type of HTML tag inside of a `section` does not get a line break (only `header` tags). E.g. a `form` tag inside of a `section` has no line break. Any ideas?

Using `article` instead of `section` gives the desired behavior, I'm just hesitate to use it since semantically - my content is belongs as a `section` and not page `article`.

(Sorry if this isn't an actual bug and understand if you want to close this ticket)

**Comment by michealp-coder** [comment]
I just figured out a fix and it's to make the `p` tag 100% wide. See the following Pull Request for more detail https://github.com/andybrewer/mvp/pull/64

**Comment by andybrewer** [comment]
Implemented: https://github.com/andybrewer/mvp/releases/tag/v1.8
