### ISSUE TITLE
Full width header/footer

### ISSUE THREAD

**Issue by willy695** [andybrewer/mvp#73]
Hi all, how do you make header full width? Like container-fluid in Twitter Bootstrap..

**Comment by andybrewer** [comment]
`footer`, `header` and `main` have padding by default: https://github.com/andybrewer/mvp/blob/master/mvp.css#L62

You can create a custom style in another styelsheet or inline in the HTML to override that.

Otherwise, `body`, `div` and `section` have no padding so they'll be full-width by default.

For example:

```
<body>
   <div>Full-width content</div>
   <main>
      <div>Padded content</div>
   </main>
</body>
```

**Comment by willy695** [comment]
Gottcha, thank you for such prompt reply, I'll simply pull the `nav` out of the `header` and create a new class for it.
